columns:
- app: [busi_name, flow, month_id]
  sms: [opposite_no_m, calltype_id, request_datetime]
  user: [city_name, county_name, idcard_cnt, arpu_201908]
  voc: [opposite_no_m, calltype_id, start_datetime, call_dur, city_name, county_name,
    imei_m]
features:
- A1:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: called_people
      para:
        months: &id001 [2020-03]
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: called_people
- A2:
  - columns:
    - voc: [call_dur, start_datetime]
    function:
    - name: num_shortcall
      para:
        months: *id001
        threshold_duration: 5
    module: ./yangli/codes_feature/short_call.py
    name: short_call
- A4:
  - columns:
    - voc: [opposite_no_m, start_datetime, call_dur]
    function:
    - name: ratio_friends
      para:
        months: *id001
        threshold_friend: 3
    module: ./yangli/codes_feature/friend_n.py
    name: ratio_friends_incall
- A5:
  - columns:
    - voc: [start_datetime, call_dur]
    function:
    - name: ratio_nonzero_calldur
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: ratio_nonzero_call_duration
- A7:
  - columns:
    - voc: [opposite_no_m, call_dur, start_datetime]
    function:
    - name: long_call
      para:
        months: *id001
        threshold_duration: 600
    module: ./hwk/codes_feature/voc_feature_hwk.py
    name: num_long_call
- A9:
  - columns:
    - voc: [opposite_no_m, start_datetime, call_dur]
    function:
    - name: mean_call_dur
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: mean_call_dur
- A10:
  - columns:
    - voc: [opposite_no_m, start_datetime, call_dur]
    function:
    - name: std_call_dur
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: std_call_dur
- A12:
  - columns:
    - voc: [opposite_no_m, start_datetime, calltype_id]
    function:
    - name: entropy_called_people
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: entropy_called_people
- A13:
  - columns:
    - voc: [start_datetime, call_dur]
    function:
    - name: ratio_zero_calldur
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: ratio_zero_calldur
- A14:
  - columns:
    - voc: [opposite_no_m, start_datetime, call_dur]
    function:
    - name: total_call_time
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_hwk.py
    name: total_call_time
- A15:
  - columns:
    - voc: [start_datetime, calltype_id]
    function:
    - name: num_callout
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: num_callout
- A16:
  - columns:
    - voc: [start_datetime, calltype_id]
    function:
    - name: num_callin
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: num_callin
- A17:
  - columns:
    - voc: [start_datetime, calltype_id]
    function:
    - name: num_calltrans
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: num_calltrans
- A18:
  - columns:
    - voc: [start_datetime, call_dur]
    function:
    - name: ratio_longcall
      para:
        months: *id001
        threshold_duration: 600
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: ratio_longcall
- A19:
  - columns:
    - voc: [start_datetime, call_dur]
    function:
    - name: ratio_shortcall
      para:
        months: *id001
        threshold_duration: 5
    module: ./yangli/codes_feature/short_call.py
    name: ratio_shortcall
- A21:
  - columns:
    - voc: [opposite_no_m, start_datetime, call_dur]
    function:
    - name: call_interval_meantime
      para:
        months: *id001
    module: ./hwk/codes_feature/voc_feature_hwk.py
    name: call_interval_meantime
- A22_min:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: first_call_time
      para:
        months: *id001
        statistics: min
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: first_call_time_min
- A22_max:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: first_call_time
      para:
        months: *id001
        statistics: max
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: first_call_time_max
- A22_mean:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: first_call_time
      para:
        months: *id001
        statistics: mean
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: first_call_time_mean
- A22_median:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: first_call_time
      para:
        months: *id001
        statistics: median
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: first_call_time_median
- A22_std:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: first_call_time
      para:
        months: *id001
        statistics: std
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: first_call_time_std
- A24_min:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: last_call_time
      para:
        months: *id001
        statistics: min
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: last_call_time_min
- A24_max:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: last_call_time
      para:
        months: *id001
        statistics: max
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: last_call_time_max
- A24_mean:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: last_call_time
      para:
        months: *id001
        statistics: mean
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: last_call_time_mean
- A24_median:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: last_call_time
      para:
        months: *id001
        statistics: median
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: last_call_time_median
- A24_std:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: last_call_time
      para:
        months: *id001
        statistics: std
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: last_call_time_std
name: all_voc_features
