columns:
- app: [busi_name, flow, month_id]
  sms: [opposite_no_m, calltype_id, request_datetime]
  user: [city_name, county_name, idcard_cnt, arpu_201908, arpu_201909, arpu_201910,
    arpu_201911, arpu_201912, arpu_202001, arpu_202002, arpu_202003]
  voc: [opposite_no_m, calltype_id, start_datetime, call_dur, city_name, county_name,
    imei_m]
features:
- A4:
  - columns:
    - voc: [opposite_no_m, start_datetime, call_dur]
    function:
    - name: ratio_friends
      para:
        months: [2019-12]
        represent_nan: -1
        threshold_friend: 3
    module: ./yangli/codes_feature/friend_n.py
    name: ratio_friends_incall
name: marginal_feature_exploration
