columns:
- app: [busi_name, flow, month_id]
  sms: [opposite_no_m, calltype_id, request_datetime]
  user: [city_name, county_name, idcard_cnt, arpu_201908, arpu_201909, arpu_201910,
    arpu_201911, arpu_201912, arpu_202001, arpu_202002, arpu_202003]
  voc: [opposite_no_m, calltype_id, start_datetime, call_dur, city_name, county_name,
    imei_m]
features:
- A43:
  - columns:
    - voc: [imei_m]
    function:
    - name: imei_num
      para:
        months: &id001 [2020-03]
        represent_nan: -10
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: number_imei
- C8:
  - columns:
    - app: [app_busi_name]
    function:
    - name: suspect_app_num
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: number_suspected_app
name: new_features
