columns:
- app: [busi_name, flow, month_id]
  sms: [opposite_no_m, calltype_id, request_datetime]
  user: [city_name, county_name, idcard_cnt, arpu_201908, arpu_201909, arpu_201910,
    arpu_201911, arpu_201912, arpu_202001, arpu_202002, arpu_202003]
  voc: [opposite_no_m, calltype_id, start_datetime, call_dur, city_name, county_name,
    imei_m]
features:
- A43:
  - columns:
    - voc: [imei_m]
    function:
    - name: imei_num
      para:
        months: &id001 [2019-08, 2019-09, 2019-10, 2019-11, 2019-12, 2020-01, 2020-02,
          2020-03]
        represent_nan: -10
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: number_imei
- C10:
  - columns:
    - app: [app_busi_name]
    function:
    - name: normal90_app_num
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: number_normal90_app
- C11:
  - columns:
    - app: [app_busi_name]
    function:
    - name: normal100_app_num
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: number_normal100_app
- C12:
  - columns:
    - app: [app_busi_name]
    function:
    - name: fraud90_app_num
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: number_fraud90_app
- C13:
  - columns:
    - app: [app_busi_name]
    function:
    - name: fraud100_app_num
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: number_fraud100_app
- C14:
  - columns:
    - app: [app_busi_name]
    function:
    - name: normal90_app_contain
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: contain_normal90_app
- C15:
  - columns:
    - app: [app_busi_name]
    function:
    - name: normal100_app_contain
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: contain_normal100_app
- C16:
  - columns:
    - app: [app_busi_name]
    function:
    - name: fraud90_app_contain
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: contain_fraud90_app
- C17:
  - columns:
    - app: [app_busi_name]
    function:
    - name: fraud100_app_contain
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: contain_fraud100_app
- C18:
  - columns:
    - app: [busi_name, flow, month_id]
    function:
    - name: normal90_flow
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: flow_normal90_app
- C19:
  - columns:
    - app: [busi_name, flow, month_id]
    function:
    - name: fraud90_flow
      para:
        months: *id001
        represent_nan: -10
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: flow_fraud90_app
- C20:
  - columns:
    - app: [busi_name, flow, month_id]
    function:
    - name: normal90_flow_normalization
      para:
        months: *id001
        represent_nan: -1
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: flow_normal90_normalization
- C21:
  - columns:
    - app: [busi_name, flow, month_id]
    function:
    - name: fraud90_flow_normalization
      para:
        months: *id001
        represent_nan: -1
    module: ./yangli/codes_feature/app_feature_liyang.py
    name: flow_fraud90_normalization
name: new_features
