columns:
- app: [busi_name, flow, month_id]
  sms: [opposite_no_m, calltype_id, request_datetime]
  user: [city_name, county_name, idcard_cnt, arpu_201908, label]
  voc: [opposite_no_m, calltype_id, start_datetime, call_dur, city_name, county_name,
    imei_m]
features:
- f1:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: called_people
      para:
        months: &id001 [2020-01, 2020-02]
    module: ./daijun/codes_feature/voc_feature.py
    name: called_people
- f2:
  - columns:
    - sms: [opposite_no_m, request_datetime]
    function:
    - name: sms_people
      para:
        months: *id001
    module: ./daijun/codes_feature/sms_feature.py
    name: sms_people
- f3:
  - columns:
    - app: [app_busi_name]
    function:
    - name: num_app
      para: {}
    module: ./daijun/codes_feature/app_feature.py
    name: num_apps
- f4:
  - columns:
    - voc: [call_dur, start_datetime]
    function:
      - name: short_call
        para:
          months: *id001
    module: ./yangli/codes_feature/short_call.py
    name: short_call
- f5:
  - columns:
    - voc: [opposite_no_m,start_datetime,call_dur]
    function:
      - name: friend_n
        para:
          months: *id001
      module: ./yangli/codes_feature/friend_n.py
      name: friend_n