name: 'call_dur'

columns:
  - user: ['city_name', 'county_name', 'idcard_cnt', 'arpu_202004']
    voc:  ['opposite_no_m', 'calltype_id', 'start_datetime', 'call_dur', 'city_name', 'county_name', 'imei_m']
    sms:  ['opposite_no_m', 'calltype_id', 'request_datetime']
    app:  ['busi_name', 'flow', 'month_id']

features:
  - f1:
      - name: 'called_people'
        columns:
          - voc: ['opposite_no_m', 'start_datetime']
        module: './daijun/codes_feature/voc_feature_yongling.py'
        function:
          - name: 'called_people'
            para: {'months': ['2020-04']}
  - f2:
      - name: 'sms_people'
        columns:
          - sms: ['opposite_no_m', 'request_datetime']
        module: './daijun/codes_feature/sms_feature_yongling.py'
        function:
          - name: 'sms_people'
            para: {'months': ['2020-04']}
  - f3:
      - name: 'num_apps'
        columns:
          - app: ['app_busi_name']
        module: './daijun/codes_feature/app_feature_yongling.py'
        function:
          - name: 'num_app'
            para:{}
  - f4:
      - columns:
          - voc: ['call_dur', 'start_datetime']
        function:
          - name: 'short_call'
            para:
              months: {'months': ['2020-04']}
        module: './yangli/codes_feature/short_call.py'
        name: 'short_call'
  - f5:
      - columns:
          - voc: ['opposite_no_m','start_datetime','call_dur']
        function:
          - name: 'friend_n'
            para:
              months: {'months': ['2020-04']}
          module: './yangli/codes_feature/friend_n.py'
          name: 'friend_n'