columns:
- app: [busi_name, flow, month_id]
  sms: [opposite_no_m, calltype_id, request_datetime]
  user: [city_name, county_name, idcard_cnt, arpu_201908, arpu_201909, arpu_201910,
    arpu_201911, arpu_201912, arpu_202001, arpu_202002, arpu_202003]
  voc: [opposite_no_m, calltype_id, start_datetime, call_dur, city_name, county_name,
    imei_m]
features:
- A36:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: active_day_num
      para:
        months: &id001 [2019-08]
    module: ./yangli/codes_feature/voc_feature_liyang.py
    name: active_day_num
- A37:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: active_interval
      para:
        months: *id001
        represent_nan: -30
    module: ./yangli/codes_feature/voc_feature_liyang.py
    name: active_interval
name: all_feature
