columns:
- app:
  - busi_name
  - flow
  - month_id
  sms:
  - opposite_no_m
  - calltype_id
  - request_datetime
  user:
  - city_name
  - county_name
  - idcard_cnt
  - arpu_201908
  - label
  voc:
  - opposite_no_m
  - calltype_id
  - start_datetime
  - call_dur
  - city_name
  - county_name
  - imei_m
features:
- f1:
  - columns:
    - voc:
      - opposite_no_m
      - start_datetime
    function:
    - name: called_people
      para:
        months: &id001
        - 2020-03
    module: ./hwk/codes_feature/voc_feature.py
    name: called_people
- f2:
  - columns:
    - sms:
      - opposite_no_m
      - request_datetime
    function:
    - name: sms_people
      para:
        months: *id001
    module: ./hwk/codes_feature/sms_feature.py
    name: sms_people
- f3:
  - columns:
    - app:
      - app_busi_name
    function:
    - name: num_app
      para: {}
    module: ./hwk/codes_feature/app_feature.py
    name: num_apps
name: call_dur
