name: 'call_dur'

columns:
  - user: ['city_name', 'county_name', 'idcard_cnt', 'arpu_201908', 'label']
    voc:  ['opposite_no_m', 'calltype_id', 'start_datetime', 'call_dur', 'city_name', 'county_name', 'imei_m']
    sms:  ['opposite_no_m', 'calltype_id', 'request_datetime']
    app:  ['busi_name', 'flow', 'month_id']

features:
  - f1:
      - name: 'called_people'
        columns:
          - voc: ['opposite_no_m', 'start_datetime']
        module: './hwk/codes_feature/voc_feature_yongling.py'
        function:
          - name: 'called_people'
            para: {'months': ['2020-01']}
  - f2:
      - name: 'sms_people'
        columns:
          - sms: ['opposite_no_m', 'request_datetime']
        module: './hwk/codes_feature/sms_feature_yongling.py'
        function:
          - name: 'sms_people'
            para: {'months': ['2020-01']}

  - f3:
      - name: 'day_call_var'
        columns:
          - voc: ['opposite_no_m', 'start_datetime','call_dur']
        module: './hwk/codes_feature/voc_feature_yongling.py'
        function:
          - name: 'day_call_var'
            para: {'months': ['2020-01']}
