columns:
- app:
  - busi_name
  - flow
  - month_id
  sms:
  - opposite_no_m
  - calltype_id
  - request_datetime
  user:
  - city_name
  - county_name
  - idcard_cnt
  - arpu_201908
  - arpu_201909
  - arpu_201910
  - arpu_201911
  - arpu_201912
  - arpu_202001
  - arpu_202002
  - arpu_202003
  voc:
  - opposite_no_m
  - calltype_id
  - start_datetime
  - call_dur
  - city_name
  - county_name
  - imei_m
features:
- A1:
  - columns:
    - voc:
      - opposite_no_m
      - start_datetime
    function:
    - name: called_people
      para:
        months: &id001
        - 2020-03
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: called_people
- A29:
  - columns:
    - voc:
      - opposite_no_m
      - start_datetime
      - calltype_id
    function:
    - name: call_in_people
      para:
        months: *id001
    module: ./yangli/codes_feature/voc_feature_liyang.py
    name: call_in_people
- A30:
  - columns:
    - voc:
      - opposite_no_m
      - start_datetime
      - calltype_id
    function:
    - name: call_out_people
      para:
        months: *id001
    module: ./yangli/codes_feature/voc_feature_liyang.py
    name: call_out_people
- B1:
  - columns:
    - sms:
      - opposite_no_m
      - request_datetime
    function:
    - name: sms_people
      para:
        months: *id001
    module: ./daijun/codes_feature/sms_feature_daijun.py
    name: sms_people
- B3:
  - columns:
    - sms:
      - opposite_no_m
      - request_datetime
    function:
    - name: sms_interval_meantime
      para:
        months: *id001
    module: ./hwk/codes_feature/sms_feature_hwk.py
    name: sms_interval_meantime
- B4:
  - columns:
    - sms:
      - opposite_no_m
      - calltype_id
      - request_datetime
    function:
    - name: ratio_sms_friends
      para:
        months: *id001
        threshold_friend: 2
    module: ./yangli/codes_feature/ratio_sms_friend_liyang.py
    name: ratio_sms_friends
- C1:
  - columns:
    - app:
      - app_busi_name
    function:
    - name: num_app
      para: {}
    module: ./daijun/codes_feature/app_feature_daijun.py
    name: num_apps
- C2:
  - columns:
    - app:
      - app_busi_name
      - flow
    function:
    - name: video_audio_flow
      para:
        months: *id001
    module: ./hwk/codes_feature/app_feature_hwk.py
    name: video_audio_flow
- C3:
  - columns:
    - app:
      - app_busi_name
      - flow
    function:
    - name: social_flow
      para:
        months: *id001
    module: ./hwk/codes_feature/app_feature_hwk.py
    name: social_flow
- C4:
  - columns:
    - app:
      - app_busi_name
      - flow
    function:
    - name: tool_flow
      para:
        months: *id001
    module: ./hwk/codes_feature/app_feature_hwk.py
    name: tool_flow
- C5:
  - columns:
    - app:
      - app_busi_name
      - flow
    function:
    - name: surf_flow
      para:
        months: *id001
    module: ./hwk/codes_feature/app_feature_hwk.py
    name: surf_flow
- C6:
  - columns:
    - app:
      - app_busi_name
      - flow
    function:
    - name: total_flow
      para:
        months: *id001
    module: ./hwk/codes_feature/app_feature_hwk.py
    name: total_flow
- D1:
  - columns:
    - user:
      - idcard_cnt
    function:
    - name: idcard_cnt
      para:
        months: *id001
    module: ./daijun/codes_feature/user_feature_daijun.py
    name: idcard_count
- D2:
  - columns:
    - user:
      - arpu_201908
      - arpu_201909
      - arpu_201910
      - arpu_201911
      - arpu_201912
      - arpu_202001
      - arpu_202002
      - arpu_202003
    function:
    - name: arpu_mean
      para:
        represent_nan: -100
    module: ./hwm/codes_feature/user_feature_hwk.py
    name: arpu_mean
- D3:
  - columns:
    - user:
      - arpu_201908
      - arpu_201909
      - arpu_201910
      - arpu_201911
      - arpu_201912
      - arpu_202001
      - arpu_202002
      - arpu_202003
    function:
    - name: arpu_std
      para:
        represent_nan: -100
    module: ./hwm/codes_feature/user_feature_hwk.py
    name: arpu_std
name: all_features
