columns:
- app:
  - busi_name
  - flow
  - month_id
  sms:
  - opposite_no_m
  - calltype_id
  - request_datetime
  user:
  - city_name
  - county_name
  - idcard_cnt
  - arpu_201908
  - arpu_201909
  - arpu_201910
  - arpu_201911
  - arpu_201912
  - arpu_202001
  - arpu_202002
  - arpu_202003
  voc:
  - opposite_no_m
  - calltype_id
  - start_datetime
  - call_dur
  - city_name
  - county_name
  - imei_m
features:
- D22:
  - columns:
    - user:
      - opposite_no_m
      - arpu_201908
      - arpu_201909
      - arpu_201910
      - arpu_201911
      - arpu_201912
      - arpu_202001
      - arpu_202002
      - arpu_202003
    function:
    - name: arpu_mean2
      para:
        months: &id001
        - 2019-12
    module: ./hwk/codes_feature/user_feature_hwk.py
    name: arpu_mean2
name: all_features