columns:
- app:
  - busi_name
  - flow
  - month_id
  sms:
  - opposite_no_m
  - calltype_id
  - request_datetime
  user:
  - city_name
  - county_name
  - idcard_cnt
  - arpu_201908
  - arpu_201909
  - arpu_201910
  - arpu_201911
  - arpu_201912
  - arpu_202001
  - arpu_202002
  - arpu_202003
  voc:
  - opposite_no_m
  - calltype_id
  - start_datetime
  - call_dur
  - city_name
  - county_name
  - imei_m
features:
- f6:
  - columns:
    - app:
      - busi_name
      - flow
    function:
    - name: total_flow
      para:
        months: &id001
          - 2019-12
    module: ./hwk/codes_feature/app_feature_hwk.py
    name: total_flow
name: all_features