name: 'call_dur'

columns:
  - user: ['city_name', 'county_name', 'idcard_cnt', 'arpu_202004']
    voc:  ['opposite_no_m', 'calltype_id', 'start_datetime', 'call_dur', 'city_name', 'county_name', 'imei_m']
    sms:  ['opposite_no_m', 'calltype_id', 'request_datetime']
    app:  ['busi_name', 'flow', 'month_id']

features:
  - f1:
      - name: 'last_call_time'
        columns:
          - voc: ['start_datetime']
        module: './yongling/codes_feature/voc_feature_yongling.py'
        function:
          - name: 'last_call_time'
            para: {'months': ['2020-04'],'statistics': 'min'}
  - f2:
      - name: 'first_call_time'
        columns:
          - voc: ['start_datetime']
        module: './yongling/codes_feature/voc_feature_yongling.py'
        function:
          - name: 'first_call_time'
            para: {'months': ['2020-04'],'statistics': 'min'}
  - f3:
      - name: 'last_sms_time'
        columns:
          - sms: ['request_datetime']
        module: './yongling/codes_feature/sms_feature_yongling.py'
        function:
          - name: 'last_sms_time'
            para: {'months': ['2020-04'],'statistics': 'min'}
  - f4:
      - name: 'first_sms_time'
        columns:
          - sms: ['request_datetime']
        module: './yongling/codes_feature/sms_feature_yongling.py'
        function:
          - name: 'first_sms_time'
            para: {'months': ['2020-04'],'statistics': 'min'}