name: 'call_dur'

columns:
  - user: ['city_name', 'county_name', 'idcard_cnt', 'arpu_202004']
    voc:  ['opposite_no_m', 'calltype_id', 'start_datetime', 'call_dur', 'city_name', 'county_name', 'imei_m']
    sms:  ['opposite_no_m', 'calltype_id', 'request_datetime']
    app:  ['busi_name', 'flow', 'month_id']

features:
  - f1:
      - name: 'calltype'
        columns:
          - voc: ['opposite_no_m','calltype_id', 'start_datetime']
        module: './yongling/codes_feature/voc_feature_yongling.py'
        function:
          - name: 'calltype_per'
            para: {'months': ['2020-04']}
  - f2:
      - name: 'sms_people'
        columns:
          - sms: ['opposite_no_m', 'request_datetime']
        module: './yongling/codes_feature/sms_feature_yongling.py'
        function:
          - name: 'sms_people'
            para: {'months': ['2020-04']}
  - f3:
      - name: 'num_apps'
        columns:
          - app: ['app_busi_name']
        module: './yongling/codes_feature/app_feature_yongling.py'
        function:
          - name: 'num_app'
            para: {}