columns:
- app:
  - busi_name
  - flow
  - month_id
  sms:
  - opposite_no_m
  - calltype_id
  - request_datetime
  user:
  - city_name
  - county_name
  - idcard_cnt
  - arpu_201908
  - label
  voc:
  - opposite_no_m
  - calltype_id
  - start_datetime
  - call_dur
  - city_name
  - county_name
  - imei_m
features:
- f1:
  - columns:
    - voc:
      - start_datetime
    function:
    - name: last_call_time
      para:
        months: &id001
        - 2019-08
        statistics: min
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: last_call_time
- f2:
  - columns:
    - voc:
      - start_datetime
    function:
    - name: first_call_time
      para:
        months: *id001
        statistics: min
    module: ./yongling/codes_feature/voc_feature_yongling.py
    name: first_call_time
- f3:
  - columns:
    - sms:
      - request_datetime
    function:
    - name: last_sms_time
      para:
        months: *id001
        statistics: min
    module: ./yongling/codes_feature/sms_feature_yongling.py
    name: last_sms_time
- f3:
  - columns:
    - sms:
      - request_datetime
    function:
    - name: first_sms_time
      para:
        months: *id001
        statistics: min
    module: ./yongling/codes_feature/sms_feature_yongling.py
    name: first_sms_time
