columns:
- app: [busi_name, flow, month_id]
  sms: [opposite_no_m, calltype_id, request_datetime]
  user: [city_name, county_name, idcard_cnt, arpu_201908]
  voc: [opposite_no_m, calltype_id, start_datetime, call_dur, city_name, county_name,
    imei_m]
features:
- f1:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: called_people
      para:
        months: &id001 [2020-03]
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: called_people
- f2:
  - columns:
    - voc: [call_dur, start_datetime]
    function:
    - name: called_people
      para:
        months: *id001
    module: ./yangli/codes_feature/short_call.py
    name: short_call
- f3:
  - columns:
    - voc: [opposite_no_m, start_datetime]
    function:
    - name: ratio_friends
      para:
        months: *id001
        threshold_friend: 3
    module: ./yangli/codes_feature/friend_n.py
    name: ratio_friends
- f4:
  - columns:
    - voc: [opposite_no_m, start_datetime, calltype_id]
    function:
    - name: entropy_called_people
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: entropy_called_people
- f5:
  - columns:
    - voc: [call_dur]
    function:
    - name: ratio_zero_calldur
      para:
        months: *id001
    module: ./daijun/codes_feature/voc_feature_daijun.py
    name: ratio_zero_calldur
name: call_dur
